# Generated by Django 3.2.8 on 2021-10-25 18:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_assessor', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Oficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_oficio', models.CharField(max_length=200)),
                ('data_emissao', models.DateField(default=datetime.date.today)),
                ('solicitante', models.EmailField(max_length=200)),
                ('em_nome_de', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_secretaria', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Vereador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_vereador', models.CharField(max_length=200)),
                ('email', models.EmailField(default='1@1.com', max_length=200)),
                ('assessor', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='Controle.assessor')),
            ],
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_tecnico', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('vereador', models.ForeignKey(default='1@1.com', on_delete=django.db.models.deletion.DO_NOTHING, to='Controle.vereador')),
            ],
        ),
    ]
